version: '3.8'
services:
  poseify-estimation:
    build:
      context: /app
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: C:/share/poseify
        target: /poseify
    networks:
      - poseify-dev-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

networks:
  poseify-dev-net:
    external: true
